dist: xenial
sudo: true
os: linux
language: java
services:
  - docker
jdk:
  - oraclejdk16
before_install:
  - chmod +x mvnw
cache:
  directories:
    - "$HOME/.m2/repository"
script:
  - sudo ./mvnw package

notifications:
  email:
    recipients:
      - alexia.becouze@epita.fr
      - paul.radic@epita.fr
      - mehdi.seddiki@epita.fr
      - valentin.thiron@epita.fr
    on_success: change
    on_failure: always