drop table if exists missions;
create table missions (id int8 generated by default as identity, beginning timestamp not null, context varchar(255) not null, description varchar(255) not null, duration int4 not null, job varchar(255) not null, location varchar(255) not null, price int4, remote float4 not null, primary key (id));

INSERT INTO missions
VALUES(1, '2021-05-12', 'intégration au sein de l’équipe Engineering du pôle Industrialisation, Cloud and Data, le consultant contribuera aux activités APIs et API Management.', 'Participer aux Comités d’Architecture pour garantir la bonne conformité des bonnes pratiques des APIs. Promouvoir les pratiques API First au sein du groupe. Rédiger / Maintenir un Guideline de développement d’API (créationde modèle d’API, ...)', 12, 'Développeur ReactJs', 'Issy-les-Moulineaux', null, 0.8);

INSERT INTO missions
VALUES(2, '2021-07-02', 'Dans la démarche de refonte de leur SI, EPITA a besoin d''une nouvelle application', 'Création d''une application permettant de recenser des missions d''une entreprise, tout en utilisant les bonnes pratiques (Clean code, architecture, tests, CI ....). Création d''une API Rest', 6, 'Stagiaire développeur Java', 'Le Kremlin-Bicêtre', null, 0.5);

INSERT INTO missions
VALUES(3, '2021-09-15', 'Ayant gagner la compétition du plus beau village français, Sancerre souhaite créer une application mobile pour valoriser son patrimoine', 'Création de maquettes Adobe XD d''une application mobile permettant de recenser les différents lieux touristiques du village', 2, 'Web Designer', 'Sancerre', 5000, 0.0);

INSERT INTO missions
VALUES(4, '2022-07-02', 'Souhaitant augmenter sa visibilité, le Château Lafon-Rochet souhaite créer un site e-commerce', 'Création du frontend d''une application permettant de commander des bouteilles ou des caisse de vin, la partie backend sera réalisée dans le même temps par un autre stagiaire', 6, 'Stagiaire développeur ReactJs', 'Bordeaux', null, 0.5);

INSERT INTO missions
VALUES(5, '2022-01-16', 'Dans la cadre de la réalisation d''une application permettant de visualiser les photos prises par les différents rovers, la Nasa a besoin d''une application Android', 'Création d''une application permettant de visualiser les photos prises par les rovers, une API est déjà existante', 1, 'Développeur Android Kotlin', 'Paris', null, 1.0);

INSERT INTO missions
VALUES(6, '2022-04-25', 'Pour la refonte de leur site vitrine, VIP Mobile a besoin d''un nouveau frontend', 'Création d''un frontend permettant de visualiser les produits et les différentes annonces de l''entreprise', 3, 'Développeur Wix', 'Belgrade', 1500, 1.0);

INSERT INTO missions
VALUES(7, '2022-03-17', 'Ayant pour devoir la rédaction d''un rapport sur le bouquetin des Alpes, un élève de l''Epita est à la recherche d''un rédacteur', 'Rédaction d''un mémoire de 50 pages sur les bouquetins des Alpes, le but étant d''étudier leur comportement', 6, 'Rédacteur', 'Barcelonnette', 500, 0.75);

INSERT INTO missions
VALUES(8, '2022-08-29', 'Dans le cadre de la production d''une nouvelle solution l''entreprise Uber a besoin d''une nouvelle application', 'Création d''une application permettant de livrer des oeuvres d''art, Uber a beosin d''une application web Java utilisant quarkus et vaadin', 5, 'Stagiaire développeur Java', 'Le Kremlin-Bicêtre', 15000, 0.8);

INSERT INTO missions
VALUES(9, '2022-05-19', 'Afin d''améliorer les compétences de leurs équipes, l''entreprise Ubisoft recherche un formateur', 'Pour développer les compétences de leurs équipes, l''entreprise Ubisoft recherche un formateur experimenté dans les moteurs de jeu. Une première formation consistera à expliquer aux développeurs comment exécuter une testsuite', 12, 'Stagiaire développeur Java', 'Montreuil', 75000, 0.25);

INSERT INTO missions
VALUES(10, '2022-06-23', 'Afin de redorer son image, l''entreprise Harmoniks a besoin d''une personne chargée de communication', 'L''entreprise Harmoniks ayant connu une année catastrophique, elle cherche à redorer son image. Une campagne publicitaire est déjà prévue. Cependant, aucune communication digitale n''est actuellement faite.', 6, 'Stagiaire chargée de communication', 'Marseille', 1, 0.0);